[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
	{ access = "write", path = "./"},
	{ access = "write", path = "../frontend"},
	{ access = "read", path = "./out/Forum.sol/Forum.json"}
]


[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"


arbitrumSepolia = "https://sepolia-rollup.arbitrum.io/rpc"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options